apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:nvEI3WZeAwdiZUPRStpe9wt2W03MF8AzlYNG8wQjMXhXvyfWOBlYmAHLWmpjN07xEpTWLibpWbiTSC5KGV4V9+smwoUd82hYsbzkC7j4sk3NlwepegzTGArs41AerbIYDwGke1QI3Cpy45R4yCcF1wFa3Uxhxn4GUAVedmiEHjI7Uix9bIjYsT6LIXD/2rcp8Fhv55pki17VvuP3Awdew1bYqztF52ghPihnvTNWdpbMKoTc2q+hUUHVkmeFcinr/JTyypD+mFqVIpQj9rq6n+MLwH3SI1MTsXkUIqcIHMSBSbW59xUvV+2HH7E=,iv:eZ+ybG3iKiaU8jIVJZ0wr8XNXUcmSfpWEtnVyFZ8a/M=,tag:ZEzQKRrgJ8epXhhoPlOUyg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age15vp2x0nncswkq9e4ymfem4y2w44gkvdx4tx5nhyu5l7q9tscu48sh77x0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaUp1aFpsVXg3YUFOTHB4
            eUJDOWlObm41MGxCUlVQMXQ5WVBTRmdTYlNBCjBNZVg3YmhtTFV4Z0JSSTV6YjhR
            d3p3N3AwbnUvZWwyS0IveFU5RlVPRHcKLS0tIFlGRGFBQVlNcVhPMVplQWk5Ylgr
            RzJpcEJxQWVUaGFyMzB5aFVVbGEzam8KUGPTEh9WWdU0xIzctTEGCFqnyrY7WJCm
            ldSdSV07eX95tD/PMJSFF6Uxpzk1NQ5gsJSuFR1Qz5vGdxRSE7fpoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T18:16:48Z"
    mac: ENC[AES256_GCM,data:HoFUGiu6m7qoh06XirwrHh1tYh3ZwU4iXg4d+xr+wCj0Bk4kYb65RmGgmKX2A7OBGdFudzsWLG3A5aeogOh9sbKjP+IayTqPVcKUKujn10IeHGcVnjM7xPpb01fk/RjlOPI7gnlv3RHhi0J1niPCc1InY9u2SXp8Zc1OWu1JOUs=,iv:jUyjHsTxEyl5STO+j7TFt20u42RuQ1UtmSRq4nw7YAA=,tag:gbhEX1yIsn20+0QZPIorgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
