apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts: ['grafana-staging.hervedelaunay.com']
        path: /
        tls:
          secretName: grafana-tls-cert
          hosts:
          - grafana-staging.hervedelaunay.com
