apiVersion: v1
data:
    password: ENC[AES256_GCM,data:a5TuQm424Ic6/pZqIp+Wqyuf8V96oqsARo7uWU8/UwOVQt96,iv:GoMEsKbrBKPbGZHp5sSoVvL4GueaZZl7e97o+H9D4yw=,tag:4Ij3Qx2CDMuNsZ4lhRR5Ew==,type:str]
    username: ENC[AES256_GCM,data:4ursrVfyq64=,iv:NzbB+NjMzSG5cnidy+IJv8HC12sOPR3e6f0GiMSHcPA=,tag:SGBEMUCZv1yAXaMscqzNLQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-credentials
sops:
    age:
        - recipient: age15vp2x0nncswkq9e4ymfem4y2w44gkvdx4tx5nhyu5l7q9tscu48sh77x0p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNWVPOVdySE0rRmIvV3hP
            d0Z1QXNMWUNqMWxoc0ZUVTBkeHRCYkNoakJNCmxIQlZzSzJjZkhGODFaSDl2azJm
            ODFrSnJhLytCSFZ3dVd2c3l3cSszdUkKLS0tIEtoZDRWcW9wMG43b0J4bFFBUjlB
            Y2pWNlBlZXRoMG9Dbk85TklmLzBYSUUK6AXu+ZGo0ykguVog1jucosGhA/gp456w
            sK1pNGMtZnTw2v9d87dz5JweMQD8loXuVbSg+7199zpDUVVIFRyrbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T19:29:09Z"
    mac: ENC[AES256_GCM,data:floe2dmI2IadChooKSP/UNElVM3hFiJpZbpDmT+2gDOEeFgFCajDTabp8vdnpfn5z5hW+Lg40lT4oqbAnHWl7YPAvQlGAkhbYhf3C0Px/Bta/gDNWXHTVfjMFWk+b6NlfvliGu3Jw5Js12IiQXevtFKRyTcAy+wDXs+v3F4SMx8=,iv:VNdOrI61GlUr3lDFCw6pRtiG0uhkPkk6CWXp1aoDvg8=,tag:FyK4y/5SNPcYI4PhWNkzfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
